### ISSUE TITLE
NMA Application Period

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Neuromatch#2]
- [x] @jesparent apply
- [x] @krishnakatyal apply (TA)
- [ ] @balicea  mentor?
- [x] @Angel1412kaitou decide on time commits 
- [ ] @EXYNOS-999  apply /decide / let us know 
- [ ] others? @convergence-excess @Shruti-Raj-Vansh-Singh @ssunidhi  etc?
- [ ] Consider project opportunities (see NEUROMATCH repo)

**Comment by jesparent** [comment]
If anyone has questions about NMA this year, feel free to ask me or @krishnakatyal  as I know we've both applied and are interested this year, and potentially doing some volunteering as well.
